apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: 
      limits:
        memory: 1G
        cpu: "2"
      requests:
        memory: 500m
        cpu: "1"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
