apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app
  name: app
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do echo "$(date) | $(du -sh ~)" >> /var/logs/diskspace.txt; sleep
      5; done;
    image: busybox
    name: app
    volumeMounts:
    - name: logs-storage
      mountPath: /var/logs
    resources: {}
  - args:
    - /bin/sh
    - -c
    - sleep 20; while true; do while read LINE; do echo "$LINE" | cut -f2 -d"|" >> $(date +%Y-%m-%d-%H-%M-%S)-transformed.txt; done < /var/logs/diskspace.txt; 
      sleep 20; done;
    image: busybox
    name: transformer
    volumeMounts:
    - name: logs-storage
      mountPath: /var/logs
    resources: {}
  volumes:
  - name: logs-storage
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
