apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello
  name: hello
spec:
  containers:
  - image: bonomat/nodejs-hello-world
    name: hello
    ports:
    - name: nodejs-port
      containerPort: 3000
    readinessProbe: # declare the readiness probe
      httpGet: # add this line
        path: / #
        port: nodejs-port #
      initialDelaySeconds: 3
    livenessProbe: # declare the readiness probe
      httpGet: # add this line
        path: / #
        port: nodejs-port #
      initialDelaySeconds: 5
      periodSeconds: 8
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
