apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: stress
  name: stress
spec:
  containers:
  - image: polinux/stress
    name: stress
    command: ["stress"]
    args: ["--cpu", "1", "--vm", "1", "--vm-bytes", "250M", "--timeout", "10s"]
    resources: 
      limits:
        memory: 200Mi
        cpu: 200m
      requests:
        memory: 100Mi
        cpu: 100m
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
