apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: backend
  name: backend
spec:
  containers:
  - image: nginx
    name: backend
    env:
    - name: DB_PASSWORD # the name you want to give
      valueFrom:
        secretKeyRef:
          name: db-credentials # name of the k8s secret
          key: db-password # key declared in the secret
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
